# Site settings
title: data-slinky
email: jknguye2@illinois.edu
description: >
  'data-driven projects + visualizations'
baseurl:
url:
twitter_username: twitter_username
github_username:  jknguye2

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /project/:path/


gems: [jekyll-paginate]